- name: install nginx 
  apt_repository: repo='ppa:nginx/stable' state=present
  tags: nginx

- name: install webserver
  apt: pkg={{item}} update_cache=yes state=latest
  with_items:
      - nginx
      - nginx-extras
      - nginx-full
  tags: nginx
