- name: Install php5 and dependencies
  apt: pkg={{item}} update_cache=yes state=latest
  with_items:
      - php5-cgi
      - php5-cli
      - php5-common
      - php5-curl
      - php5-dev
      - php5-fpm
      - php5-gd
      - php5-imap
      - php5-mcrypt
      - php5-memcache
      - php5-mysql
      - php5-fpm
  tags:
      - php5-base
      - php5
